Add the ability to require a file on disk for crons to run
In our environment, the designation of primary cron host is indirectly
managed through the existence of a file on disk. We want cron jobs
running only on the host that has this file; a cron job running on a
host without this file should exit without executing.

Add this capability to cron-runner, controlled through the
`CRON_VERIFY_ACTIVE` and `CRON_ACTIVE_FILE` environment variables. The
former accepts a boolean value and controls whether cron-runner tests
for the existence of the file path in the latter.

If the file doesn't exist, or we can't determine that fact due to
folder permissions, cron-runner will exit early and log an error to
stderr:

```
ERROR: Unable to stat CRON_ACTIVE_FILE:<error message>
```